### PR TITLE
1.11.2

### PR DESCRIPTION
**Pull request by OathtakerPaladin**
Ported Ex Compressum to 1.11.2 as best I could, using the 1.11.2 branch of Ex Nihilo Adscensio. Had to (temporarily) disable support for Omnia.

Bulk of the work is updating the mod to work for 1.11, but there's also changes to update the support for JEI.

### CODE REVIEW

**Comment by OathtakerPaladin** [comment]
Versions of mods built against:
Baubles-1.11-1.4.5
Botania r1.9-343
compatlayer-1.11.2-0.2.9
CraftTweaker-1.11.2-3.0.25
[Ex Nihilo Adscensio (1.11.2 Branch)](https://github.com/MikeLydeamore/ExNihiloAdscensio/tree/1.11.2)
jei_1.11.2-4.3.6.282
Mantle-1.11.2-1.2.0.26
TConstruct-1.11.2-2.7.0.27
theoneprobe-1.1x-1.4.7
Waila-1.7.1_1.11.2

**Comment by blay09** [comment]
No official release for now since there's still some TODOs to do and the Ex Nihilos haven't updated yet, but it's [building on my Jenkins](http://jenkins.blay09.net/job/Ex%20Compressum%201.11.2/). 

Some post-mortem notes:
- ItemStack has `shrink` and `grow` methods that look nicer than `.setCount(.getCount() ...)`
- Vanilla classes come with `@MethodsReturnNonnullByDefault` and `@ParametersAreNonnullByDefault` package-wide, so I do the same rather than using `@Nonnull` to stay closer to Vanilla
- Removing an `@Override` because it doesn't compile with it isn't good, the method signature had to be updated
- The `@SuppressWarnings` I was using were there intentionally, they help porting by having code analysis not report them as warnings. Vanilla marks a lot of things deprecated without actually having a replacement for them, and when it does remove things they're gone without backwards compatibility anyways, so it can be safely ignored.

**Comment by OathtakerPaladin** [comment]
I'm glad I could be of some help.

Now knowing that there is `shrink` and `grow` after looking in the ItemStack class makes me realize how much easier that would have been to change, and makes me wonder how I didn't find it before.

I will also take note of the Vanilla annotations.

A commented `@Override` must have been an error on my part, and I can assure you that was not intentional. If it isn't a bother, do you recall where that mistake was? The one I can see is the Ex Omnia compatible mesh, which was commented out as there wasn't, and still isn't a compatible branch to build against.

Finally, the `@SuppressWarnings` I removed should have only been suppressions that didn't suppress anything anymore, however if I was overzealous, or if my IDE is a bit stringent on what counts as a useless annotation, my apologies.

Thank you for the tips, I will no doubt use them in the future. Especially that `shrink` and `grow` thing, that's honestly quite embarrassing on my part. I apologize for any inconvenience I may have caused, and I hope I was still helpful otherwise.

**Comment by blay09** [comment]
It was `getCollisionBoundingBoxes` in BlockBait, parameter `World` became `IBlockAccess`.

And no worries, you did take quite a bit of work off me. I forgot to thank you in my initial post. :P

**Comment by OathtakerPaladin** [comment]
Ah, yes I recall that now. I remember I couldn't figure out what was wrong with the signature, and Eclipse wasn't helping, so it wasn't until I discovered McJty's rather helpful list of "Gotcha!" changes that I learned to handle that specific change. Of course I got it right when I helped port Clumps. I just completely forgot to come back and fix it here too.

**Pull request merged**
